name: CEZESSENTIALS
version: 1.0.0
main: com.clipson.cezessentials.CEZEssentialsPlugin
api-version: '1.21'
author: clippyclip
description: Clean, modular Essentials-style plugin

commands:
  cezhelp:
    description: Show available commands
    permission: cezessentials.help
  cezreload:
    description: Reload CEZESSENTIALS
    permission: cezessentials.reload

  spawn:
    description: Teleport to spawn
    permission: cezessentials.spawn
  setspawn:
    description: Set spawn
    permission: cezessentials.setspawn

  home:
    description: Teleport home
    permission: cezessentials.home
  sethome:
    description: Set home
    permission: cezessentials.sethome
  delhome:
    description: Delete home
    permission: cezessentials.delhome

  warp:
    description: Teleport to a warp
    permission: cezessentials.warp
  setwarp:
    description: Set a warp
    permission: cezessentials.setwarp
  delwarp:
    description: Delete a warp
    permission: cezessentials.delwarp

  tpa:
    description: Request teleport
    permission: cezessentials.tpa
  tpaccept:
    description: Accept teleport
    permission: cezessentials.tpaccept
  tpdeny:
    description: Deny teleport
    permission: cezessentials.tpdeny
